name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - run: |
        GOOS=windows GOARCH=amd64 go build -o iwmon.exe -v -ldflags "-s -w" ./...
        GOOS=linux GOARCH=amd64 go build -o iwmon -v -ldflags "-s -w" ./...

